name: NewImage
on:
  push:
    branches:
      - master

jobs:
  first-job:
    name: UpdateImage
    runs-on: ubuntu-latest
    steps:
        - name: Checkout 
          uses: actions/checkout@v3
        - name: Log into Dockerhub 
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Build with Docker
          uses: docker/setup-buildx-action@v1
        - uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: "${{ secrets.DOCKERHUB_IMAGE }}"
